spring.application.name=earthquakes
spring.profiles.active=local

# Database
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# USGS client
earthquakes.usgs.base-url=https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary
earthquakes.usgs.feed=all_day.geojson